### ISSUE TITLE
unable to install the package 

### ISSUE THREAD

**Issue by VenkiRaoNTP** [gartner/palustris-tinymce-input#1]
yarn add @palustris/tinymce-input
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@palustris%2ftinymce-input: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/venkirao/Projects/ntpages/ntp/www/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by gartner** [comment]
The examples from the README used a wrong package name. The correct one is @palustris/ra-tinymce-input
